### ISSUE TITLE
Add addSeries(Collection<AddSeriesCommand>) to DataService

### ISSUE THREAD

**Issue by Arthasasyan** [axibase/atsd-api-java#66]
At the moment we have `addSeries` method defined only for vararg

```java
/**
     * @param addSeriesCommands commands that contains time-series which are added
     * @return true if success
     */
    public boolean addSeries(AddSeriesCommand... addSeriesCommands) {
        for (AddSeriesCommand addSeriesCommand : addSeriesCommands) {
            checkEntityIsEmpty(addSeriesCommand.getEntityName());
            checkMetricIsEmpty(addSeriesCommand.getMetricName());
        }
        QueryPart<Series> query = new Query<Series>(SERIES_KEYWORD)
                .path(INSERT_KEYWORD);
        return httpClientManager.updateData(query,
                post(Arrays.asList(addSeriesCommands)));
    }
```

I suppose, it would be useful to add allies with `Collecion` argument type

```java
/**
     * @param addSeriesCommands commands that contains time-series which are added
     * @return true if success
     */
    public boolean addSeries(Collection<AddSeriesCommand> addSeriesCommands) {
        for (AddSeriesCommand addSeriesCommand : addSeriesCommands) {
            checkEntityIsEmpty(addSeriesCommand.getEntityName());
            checkMetricIsEmpty(addSeriesCommand.getMetricName());
        }
        QueryPart<Series> query = new Query<Series>(SERIES_KEYWORD)
                .path(INSERT_KEYWORD);
        return httpClientManager.updateData(query,
                post(addSeriesCommands));
    }

    public boolean addSeries(AddSeriesCommand... addSeriesCommands) {
    return addSeries(Arrays.asList(addSeriesCommand);
}

**Comment by raipc** [comment]
I don't see a reason to extend the API that is not even known to be used

**Comment by Arthasasyan** [comment]
I'm not sure that the lack of current users should prevent us from improving functionality.

**Comment by raipc** [comment]
I'm not sure adding 23rd public method is an improvement. Real improvements are: code deduplication, removing of dead code (if sure that no one client can use it, i.e. not public), specialization for performance-sensible code (after proof that this change increases performance significantly). But in this class most methods are vararg, so duplicating one would lead to duplicating others. When the time comes, a better way to refactor this code would be to deprecate the whole service and create another one that fits user's needs in collection usage. Until then let's keep the API as is.
