### ISSUE TITLE
Obsolete entity-and-tags url

### ISSUE THREAD

**Issue by unrealwork** [axibase/atsd-api-java#72]
In this API we use obsolete url `/api/v1/metrics/{name}/entity-and-tags` which is not documented and was deleted in axibase/tsd#1140

**Comment by unrealwork** [comment]
@rodionos 
Should the old URL be reverted? Or should API code be migrated on new documented `/api/v1/metrics/{name}/series` URL?

**Comment by raipc** [comment]
@unrealwork 
Old URL should be available since we have clients who use many collectors and write to a single ATSD. If response format is the same, entity-and-tags may delegate to the new API

**Comment by rodionos** [comment]
Lets keep the old URL to spare ourselves time on finding it which integrations depend on it.
